### ISSUE TITLE
about fp16

### ISSUE THREAD

**Issue by 666zz666** [vacancy/Synchronized-BatchNorm-PyTorch#22]
When I use fp16 (16-bit float) and multi-gpu training,the code will wait in SyncBN(comm.py).
![tim 20190220212250](https://user-images.githubusercontent.com/31818905/53094740-f6c35700-3555-11e9-8960-939a8b1ca922.png)

**Comment by vacancy** [comment]
I haven’t tried fp16 in pytorch. Do you think it’s due to some type mismatch: fp32 vs. fp16? It will be great if you could help me to add a try-catch in the forward method of the batch norm class. We should first check if some exceptions have been thrown out there.

**Comment by 666zz666** [comment]
Thanks for your help .Firstly,I am using two gpus. Secondly,I add a try-catch in the forward method of the _SynchronizedBatchNorm class(batchnorm.py).Then ,I locate the error step by step.

![error1](https://user-images.githubusercontent.com/31818905/53096916-2de83700-355b-11e9-8bba-8227fb2cc1b0.png)
![error2](https://user-images.githubusercontent.com/31818905/53096925-30e32780-355b-11e9-8dd8-0e048089e5ab.png)
![error4](https://user-images.githubusercontent.com/31818905/53096939-3e001680-355b-11e9-8f29-8888f4c7e21f.png)
![error5](https://user-images.githubusercontent.com/31818905/53096945-41939d80-355b-11e9-9859-6df4ef29c60f.png)

**Comment by 666zz666** [comment]
Thanks for your help .Firstly,I am using two gpus. Secondly,I add a try-catch in the forward method of the _SynchronizedBatchNorm class(batchnorm.py).Then ,I locate the error step by step.

### 1. batchnorm.py:
        if self._parallel_id == 0:
            mean, inv_std = self._sync_master.run_master(_ChildMessage(input_sum, input_ssum, sum_size))

### 2.comm.py:
    results = self._master_callback(intermediates)

### The error is 'An error occured.'
### My try-catch like this:

except IOError:
    print('An error occured trying to read the file.')
    
except ValueError:
    print('Non-numeric data found in the file.')

except ImportError:
    print "NO module found"
    
except EOFError:
    print('Why did you do an EOF on me?')

except KeyboardInterrupt:
    print('You cancelled the operation.')

except:
    print('An error occured.')

**Comment by vacancy** [comment]
Can you give detailed information about the "error"?

For example, you may directly wrap the whole function body of `forward()` with a try-catch statement:

```
try:
    # original codes
except:
    import traceback
    traceback.print_exc()
```

**Comment by 666zz666** [comment]
### The detailed information
Traceback (most recent call last):
  File "/mnt/data-2/data/cnn_multi_/cnn_multi/sync_batchnorm/batchnorm.py", line 68, in forward
    mean, inv_std = self._sync_master.run_master(_ChildMessage(input_sum, input_ssum, sum_size))
  File "/mnt/data-2/data/cnn_multi_/cnn_multi/sync_batchnorm/comm.py", line 125, in run_master
    results = self._master_callback(intermediates)
  File "/mnt/data-2/data/cnn_multi_/cnn_multi/sync_batchnorm/batchnorm.py", line 108, in _data_parallel_master
    mean, inv_std = self._compute_mean_std(sum_, ssum, sum_size)
  File "/mnt/data-2/data/cnn_multi_/cnn_multi/sync_batchnorm/batchnorm.py", line 122, in _compute_mean_std
    mean = sum_ / size
RuntimeError: value cannot be converted to type at::Half without overflow: 528392

**Comment by vacancy** [comment]
Seems that some values in the tensors exceed the max value of fp16 ... I guess it's the `size`? Can you double check?

I am not an expert on this: is there any solution to this? I think this should be a general problem for fp16 training.
